export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESSFUL = "PRODUCT_LIST_SUCCESSFUL";
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESSFUL = "PRODUCT_DETAILS_SUCCESSFUL";
export const PRODUCT_DETAILS_FAILED = "PRODUCT_DETAILS_FAILED";
